name: xtm-connect-sdk-php
type: php-library

php:
  version: 8.1-cli-bullseye
  phpcs:
    standard: PSR12
  phpstan:
    level: max

dockerfile:
  stages:
    build:
      extends: base
      packages:
        - git
        - unzip
      commands:
        - composer validate --strict
        - composer install

    test:
      extends: build
      commands:
        - parallel-lint src --no-progress
        - phpcs -vv
        - phpstan
        - phpunit --testdox
